### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by jmokoistinen** [chriswolfvision/local_adaptive_binarization#1]
Seems I cannot compile it on Ubuntu 16.04 linux, which Opencv version did you use?

make
g++ -I/usr/include/opencv binarizewolfjolion.cpp -o binarizewolfjolion `pkg-config opencv --libs`-lstdc++
binarizewolfjolion.cpp:1:24: error: ‘Mat’ was not declared in this scope
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                        ^
binarizewolfjolion.cpp:1:29: error: ‘im’ was not declared in this scope
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                             ^
binarizewolfjolion.cpp:1:33: error: ‘Mat’ was not declared in this scope
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                 ^
binarizewolfjolion.cpp:1:38: error: ‘map_m’ was not declared in this scope
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                      ^
binarizewolfjolion.cpp:1:45: error: ‘Mat’ was not declared in this scope
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                             ^
binarizewolfjolion.cpp:1:50: error: ‘map_s’ was not declared in this scope
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                                  ^
binarizewolfjolion.cpp:1:57: error: expected primary-expression before ‘int’
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                                         ^
binarizewolfjolion.cpp:1:67: error: expected primary-expression before ‘int’
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                                                   ^
binarizewolfjolion.cpp:1:75: error: expression list treated as compound expression in initializer [-fpermissive]
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                                                           ^
binarizewolfjolion.cpp:1:77: error: expected ‘,’ or ‘;’ before ‘{’ token
 double calcLocalStats (Mat &im, Mat &map_m, Mat &map_s, int winx, int winy) {    
                                                                             ^
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by beardeer** [comment]
Same problem here, I have OpenCV 2.4.9, should we use OpenCV 3? Please help, thanks!

**Comment by beardeer** [comment]
Fixed, version 4bd25b106c87b6b1a449127873c568c50e691887 works.

**Comment by ceztko** [comment]
@beardeer It's not fixed at all! 4bd25b1 is a previous commit, meaning the most recent version, which should include improvements, was left broken.

**Comment by chriswolfvision** [comment]
Hi guys,

I am sorry, I didn't have time to maintain this for a long time, and apparently some commit terribly broke things. Actually, all functions where there, but the main() test function and some declarations were missing.

I added the files, updated the Makefile for ubuntu 18 and tested it.
It works.

Christian

**Comment by beardeer** [comment]
Hi @chriswolfvision, thanks for your work! This project is awesome!!
