### ISSUE TITLE
class cv::Mat has no member fset

### ISSUE THREAD

**Issue by AliceDinh** [chriswolfvision/local_adaptive_binarization#2]
In your code, there is this part that contain fset function that could not be found, please check for me. I am using OpenCV3.0 VisualStudio2015
                       `if (j == y_firstth)
				for (int u = 0; u<y_firstth; ++u)
					thsurf.fset(i + wxh, u, th);`
			`if (j == y_lastth)
				for (int u = y_lastth + 1; u<im.rows; ++u)
					thsurf.fset(i + wxh, u, th);`

**Comment by chriswolfvision** [comment]
Hi, 
sorry, this is a really old issue, I know.
Anyway, fset is a macro, not a member function of cv::Mat.
There is no problem on Ubuntu, and I don't work on Windows, sorry.

Christian
